# You may need to change this line for your real project.
baseURL = 'Ed.'

title = "Nahi"
enableRobotsTXT = true
refLinksErrorLevel = "WARNING"

[params]
  description = "Nahi Khan"
  keywords = ["Nahi Khan", "blog", "projects"]
  tagline = ""
  footer = "© 2024 Nahi Khan. Built with Ed."
  colorScheme = ""
  mainSections = ["posts", "projects", "about"]
  readmore = true
  feedSize = 25
  recentPostsSize = 5
  showAuthor = true

[params.author]
  name = "Nahi Khan"

[params.search]
  maxSummaryLength = 100
  languages = ["en"]

[params.comments]
  enable = false
  type = "giscus"

[pagination]
  pagerSize = 10

[menus]
  [[menus.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 1

  [[menus.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 2

  [[menus.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 4

[module]
  [module.hugoVersion]
    extended = true
    min = "0.121.0"
  [[module.imports]]
    path = "github.com/sergeyklay/gohugo-theme-ed"